platform :ios, '10.0'
use_frameworks!

workspace 'ServerlessSwift'

target 'ServerlessSwiftClient' do
   project 'ServerlessSwiftClient/ServerlessSwiftClient'  
   pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '3.1.0' 
end
